/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectomate;

import javax.swing.JOptionPane;

/**
 *
 * @author Kevin
 */
public class frmSistemaEcuaciones extends javax.swing.JFrame {

    /**
     * Creates new form frmSistemaEcuaciones
     */
    public frmSistemaEcuaciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtL2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        txt4 = new javax.swing.JTextField();
        txt3 = new javax.swing.JTextField();
        txtL1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtK12 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtK11 = new javax.swing.JTextField();
        txtK22 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtK21 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtY = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtX = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtL2.setEditable(false);
        txtL2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Sistema de ecuaciones matriz 2x2");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("L1");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 100)); // NOI18N
        jLabel2.setText("]");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("L2");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/if_Delete_2290850.png"))); // NOI18N
        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/if_qr_code_2639895.png"))); // NOI18N
        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/if_logout_173050.png"))); // NOI18N
        jButton3.setText("Regresar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 100)); // NOI18N
        jLabel3.setText("[");

        txt1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        txt2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        txt4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        txt3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        txtL1.setEditable(false);
        txtL1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("K2");

        txtK12.setEditable(false);
        txtK12.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("K1");

        txtK11.setEditable(false);
        txtK11.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        txtK22.setEditable(false);
        txtK22.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("K1");

        txtK21.setEditable(false);
        txtK21.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("K2");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Y: ");

        txtY.setEditable(false);
        txtY.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("X: ");

        txtX.setEditable(false);
        txtX.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(198, 984, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtL2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(txt4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(45, 45, 45)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtL1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtK12, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtK11, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtK21)
                                            .addComponent(txtK22)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtY)
                                    .addComponent(txtX))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt4))
                        .addGap(164, 164, 164))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel4)
                                            .addComponent(txtL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7)
                                            .addComponent(txtK11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtK12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtL2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtK21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel8))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtK22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel9)))
                                            .addComponent(jLabel5))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        txt1.setText("");
        txt2.setText("");
        txt3.setText("");
        txt4.setText("");
        txtL1.setText("");
        txtL2.setText("");
        txtK11.setText("");
        txtK12.setText("");
        txtK21.setText("");
        txtK22.setText("");
        txtX.setText("");
        txtY.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (txt1.getText().isEmpty() || txt2.getText().isEmpty() || txt3.getText().isEmpty() || txt4.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Ingrese todos los valores");
            return;
        }
        try {
            //aqui es donde obtiene los valores según la posicion en la matriz de izquierda a derecha y de arriba a abajo. (v1,v2,v3,v4)
            double v1 = Double.parseDouble(txt1.getText()), v2 = Double.parseDouble(txt2.getText()), v3 = Double.parseDouble(txt3.getText()), v4 = Double.parseDouble(txt4.getText());

            //entero es la parte entera de la ecuacion cuadratica resultante de la operacion, variable el coeficiente que acompaña a lambda
            //y variable cuadrado es el coeficiente que acompaña a lambda cuadrado
            double entero, variable, variableCuadrado;

            entero = ((v1 * v4) - (v2 * v3));
            variable = (v1 * (-1)) + (v4 * (-1));
            variableCuadrado = 1;

            //aqui verifica si la respuesta sería un número imaginario, utilizando el discriminante b^2-4ac<0
            if ((Math.pow(variable, 2)) - (4 * entero * variableCuadrado) < 0) {

                double valorBeta; //variable que tomará el valor de alfa del teorema
                double valorAlfa = ((-1) * variable) / (2 * variableCuadrado); //variable que tomará el valor beta del teorema

                valorBeta = (Math.sqrt(((Math.pow(variable, 2)) - (4 * entero * variableCuadrado)) * (-1))) / (2 * variableCuadrado);

                //muestra las raices de lambda
                txtL1.setText(String.valueOf(valorAlfa + "+" + valorBeta + "i"));
                txtL2.setText(String.valueOf(valorAlfa + "-" + valorBeta + "i"));

                //B es la matriz que se utiliza para la respuesta final del problema, donde B11 y B12 son la parte real, B21 y B22 son la parte imaginaria
                double B11 = 1;
                double B12 = (valorAlfa - v1) / v2;
                double B21 = 0;
                double B22 = (valorBeta) / v2;

                //sólo se muestran los valores de k para lambda1 y no k2 ya que no es necesario para la resolucion del problema
                txtK11.setText("1");
                txtK12.setText(((valorAlfa - v1) / v2) + "+" + valorBeta / v2 + "i");
                txtK21.setText("");
                txtK22.setText("");

                //aqui muestra la respuesta ya escrita con los valores correspondientes
                txtX.setText("C1[(" + B11 + "Cos(" + valorBeta + "t)-" + B21 + "Sen(" + valorBeta + "t)]e^" + valorAlfa + "t  +  C2[(" + B21 + "Cos(" + valorBeta + "t)+" + B11 + "Sen(" + valorBeta + "t)]e^" + valorAlfa + "t");
                txtY.setText("C1[(" + B12 + "Cos(" + valorBeta + "t)-" + B22 + "Sen(" + valorBeta + "t)]e^" + valorAlfa + "t  +  C2[(" + B22 + "Cos(" + valorBeta + "t)+" + B12 + "Sen(" + valorBeta + "t)]e^" + valorAlfa + "t");

            } else {

                //cuadraticaMenos y Mas son las varibles que almacenan las raices de lambda.
                double cuadraticaMenos;
                double cuadraticaMas;

                cuadraticaMenos = (((-1) * variable) - Math.sqrt((Math.pow(variable, 2)) - (4 * entero * variableCuadrado))) / (2 * variableCuadrado);

                cuadraticaMas = (((-1) * variable) + Math.sqrt((Math.pow(variable, 2)) - (4 * entero * variableCuadrado))) / (2 * variableCuadrado);

                txtL1.setText(String.valueOf(cuadraticaMas));
                txtL2.setText(String.valueOf(cuadraticaMenos));

                //Proceso para obtener k1 con lambda1
                double v11;

                v11 = v1 - cuadraticaMas;

                double k11, k12;

                k11 = v11;
                k12 = (-v2);

                if (k11 == k12) {
                    k11 = 1;
                    k12 = 1;
                }

                if ((k11 < 0) && (k12 < 0)) {
                    k11 = -k11;
                    k12 = -k12;
                }
                //For para simplificar las expresiones en K
                for (int i = 2; i < 10; i++) {

                    if ((k11 % i == 0) && (k12 % i == 0)) {
                        k11 = k11 / i;
                        k12 = k12 / i;
                    }
                }
//                if((k11 % 2 == 0) && (k12 % 2 == 0)){
//                    k11 = k11 / 2;
//                    k12 = k12 / 2;
//                }

                txtK11.setText(String.valueOf(k11));
                txtK12.setText(String.valueOf(k12));

                //Si las Lambda son diferentes va a seguir con el proceso normal, de lo contrario si son repetidas hay que hacer otro procedimiento
                if (cuadraticaMas != cuadraticaMenos) {

                    //Lambda 2
                    double v12;

                    v12 = v1 - cuadraticaMenos;

                    double k21, k22;

                    k21 = v12;
                    k22 = (-v2);

                    if (k21 == k22) {
                        k21 = 1;
                        k22 = 1;
                    }
                    for (int i = 2; i < 10; i++) {

                        if ((k21 % i == 0) && (k22 % i == 0)) {
                            k21 = k21 / i;
                            k22 = k22 / i;
                        }
                    }
//                    if((k21 % 2 == 0) && (k22 % 2 == 0)){
//                        k21 = k21 / 2;
//                        k22 = k22 / 2;
//                    }

                    txtK21.setText(String.valueOf(k21));
                    txtK22.setText(String.valueOf(k22));

                    txtX.setText(k11 + " C1 e^" + cuadraticaMas + "t + " + k21 + " C2 e^" + cuadraticaMenos + "t");
                    txtY.setText(k12 + " C1 e^" + cuadraticaMas + "t + " + k22 + " C2 e^" + cuadraticaMenos + "t");
                } else {
                    //implementación del codigo con eignevalores repetidos.
                    //(A-LambdaI)P = K
                    //Con P1 = 0
                    double p1, p2;
                    p1 = 0;
                    p2 = k11 / v2;
                    System.out.println(p2);
                    txtX.setText(k11 + "C1 e^" + cuadraticaMas + "t + " + k11 + "C2te^ " + cuadraticaMas);
                    txtY.setText(k12 + "C1 e^" + cuadraticaMas + "t + " + k12 + "C2[te^ " + cuadraticaMas + " + " + p2 + "e^" + cuadraticaMas + "t]");
                }
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Valores inconsistentes");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
        frmMenu nueva1 = new frmMenu();
        nueva1.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextField txtK11;
    private javax.swing.JTextField txtK12;
    private javax.swing.JTextField txtK21;
    private javax.swing.JTextField txtK22;
    private javax.swing.JTextField txtL1;
    private javax.swing.JTextField txtL2;
    private javax.swing.JTextField txtX;
    private javax.swing.JTextField txtY;
    // End of variables declaration//GEN-END:variables
}
