/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectomate;

import javax.swing.JOptionPane;

/**
 *
 * @author asael
 */
public class TablaTransformadas extends javax.swing.JDialog {

    /**
     * Creates new form TablaTransformadas
     */
    public TablaTransformadas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListFunciones = new javax.swing.JList<>();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Transformada = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setText("Funcion:");

        ListFunciones.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " 1", " t", " t^n", " e^(at)", " t^(n)*e^(at)", " cos (kt)", " sin (kt)", " cosh (kt)", " sinh (kt)", " e^(at) * cos (kt)", " e^(at) * sin (kt)", " (1/(2k)^3 ) * (sin (kt) -kt * cos(kt)) ", " (1/2k) * sin (kt)", " (1/2k) * (sin (kt) + kt * cos(kt))", " u* (t-a)" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ListFunciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListFuncionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ListFunciones);

        btnBack.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-flecha-apuntando-hacia-la-izquierda-30.png"))); // NOI18N
        btnBack.setText("Regresar");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel2.setText("Transformada:");

        Transformada.setColumns(20);
        Transformada.setRows(5);
        jScrollPane2.setViewportView(Transformada);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE))
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void ListFuncionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListFuncionesMouseClicked
        try {
        if(ListFunciones.getSelectedIndex()>=0){
            int opcion=ListFunciones.getSelectedIndex();
            int a;
            int n;
            int k;
            switch(opcion){
                case 0:                    
                    Transformada.setText("1/s");
                    break;
                case 1:
                    Transformada.setText("1/s^2");
                    break;
                case 2:
                    n=Integer.parseInt(JOptionPane.showInputDialog("Ingrese el n"));
                    Transformada.setText(factorial(n)+"/s^"+(n+1));
                    break;
                case 3:                    
                    a=Integer.parseInt(JOptionPane.showInputDialog("Ingrese el a"));
                    Transformada.setText("1/(s -"+a+")");
                    break;
                case 4:
                    a=Integer.parseInt(JOptionPane.showInputDialog("Ingrese el  a"));
                    n=Integer.parseInt(JOptionPane.showInputDialog("Ingrese el  n"));
                    Transformada.setText(factorial(n)+"/(s - "+a+")^"+(n+1));
                    break;
                case 5:
                    k=Integer.parseInt(JOptionPane.showInputDialog("Ingrese el k"));
                    Transformada.setText("s/(s^2 + "+Math.pow(k,2)+")");
                    break;
                case 6:
                    k=Integer.parseInt(JOptionPane.showInputDialog("Ingrese el k"));
                    Transformada.setText(k+" /(s^2 + "+Math.pow(k,2)+")");
                    break;
                case 7:
                    k=Integer.parseInt(JOptionPane.showInputDialog("Ingrese el k"));
                    Transformada.setText("s/(s^2 - "+Math.pow(k,2)+")");                    
                    break;
                case 8:
                    k=Integer.parseInt(JOptionPane.showInputDialog("Ingrese el k"));
                    Transformada.setText(k+"/(s^2 - "+Math.pow(k,2)+")");
                    break;
                case 9:                    
                    a=Integer.parseInt(JOptionPane.showInputDialog("Ingrese el a"));
                    k=Integer.parseInt(JOptionPane.showInputDialog("Ingrese el k"));
                    Transformada.setText("s - "+a+"/((s - "+a+")^2 + "+Math.pow(k,2)+")");
                    break;
                case 10:
                    a=Integer.parseInt(JOptionPane.showInputDialog("Ingrese el a"));
                    k=Integer.parseInt(JOptionPane.showInputDialog("Ingrese el k"));
                    Transformada.setText(k+" /((s - "+a+")^2 + "+Math.pow(k,2)+")");
                    break;
                case 11:                    
                    k=Integer.parseInt(JOptionPane.showInputDialog("Ingrese el k"));
                    Transformada.setText("1/((s^2 + "+Math.pow(k,2)+")^2");                   
                    break;
                case 12:
                    k=Integer.parseInt(JOptionPane.showInputDialog("Ingrese el k"));
                    Transformada.setText("s/((s^2 + "+Math.pow(k,2)+")^2");
                    break;
                case 13:                    
                    k=Integer.parseInt(JOptionPane.showInputDialog("Ingrese el k"));
                    Transformada.setText("s^2/((s^2 + "+Math.pow(k,2)+")^2");                    
                    break;                
                case 14:                    
                    a=Integer.parseInt(JOptionPane.showInputDialog("Ingrese el a"));
                    Transformada.setText("e^(-"+a+"s)/s");                    
                    break;                
            }           
        }
        }catch(java.lang.NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Ingrese el valor correcto");
        }
    }//GEN-LAST:event_ListFuncionesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> ListFunciones;
    private javax.swing.JTextArea Transformada;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    public static int factorial(int numeros){//pide como parametro el numero del factorial
        int respuesta=1; //creacion e inicializacion de una variable
        String retorno="";
        int numero=numeros;
        for(int contador=1;contador<=numero;contador++){//ciclo que inicia en un y termina en el numero que se pide por parametro
            respuesta=respuesta*contador;            //multiplica todos los numeros desde el 1 hasta el numero
        }
        retorno+=respuesta;
        return respuesta;//regresa la respuesta
    }
}
